export const TOOL_MODEL_CONTENT_MAX_CHARACTERS = 2_000;
export const TOOL_DETAILS_MAX_SERIALIZED_CHARACTERS = 32_000;
export const TOOL_DETAILS_MAX_PACKAGES = 50;
export const TOOL_DETAILS_MAX_DESCRIPTION_CHARACTERS = 240;
export const TOOL_DETAILS_MAX_OUTPUT_CHARACTERS = 1_000;
export const TOOL_DETAILS_MAX_KEYWORDS = 20;
export const TOOL_DETAILS_MAX_CAPABILITIES = 12;
export const TOOL_COLLAPSED_PACKAGE_PREVIEW = 3;
